name: flutter_bluetooth_serial_example
version: 1.0.0
description: Demonstrates how to use the `flutter_bluetooth_serial` plugin.
homepage: https://github.com/edufolly/flutter_bluetooth_serial/tree/master/example/

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  scoped_model: ^2.0.0
  cupertino_icons: ^1.0.8
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_bluetooth_serial:
    path: ../
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
